apiVersion: v1
kind: Pod
metadata:
  name: hook-postinstall
  annotations:
    "helm.sh/hook": "post-install"
spec:
  containers:
  - name: hook2-container
    image: nginx
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo post-install hook Pod is running - hook-postinstall && curl https://www.freshcells.de/some/api']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0  